name: Liquid Build
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm install
      - name: Render
        run: node script/render.js
      - name: Package
        run: node script/package.js
