name: Liquid Build
on: 
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v5
      - name: checkout liquid-build
        uses: actions/checkout@v5
        with:
          repository: 'kkiris/liquid-build'
          path: liquid-build
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
        working-directory: liquid-build
      - name: Render Templates
        run: node liquid-build/script/render.js
        working-directory: ${{ github.workspace }}
        env:
          NODE_PATH: ${{ github.workspace }}/liquid-build/node_modules
      - name: Package Builds
        run: node liquid-build/script/package.js
        working-directory: ${{ github.workspace }}
        env:
          NODE_PATH: ${{ github.workspace }}/liquid-build/node_modules
